name: visual-programming
favicon: null
layout_spectrum: 0.11507149855606258
typography_spectrum: 0.9171032328158617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cedef7'
    - '#101721'
    - '#8f8f91'
    - '#30404f'
    - '#ae7343'
  brandStrength: 0.32661159755662084
  lightness: 0.8344594656955451
  saturation: 0.35672578192315996
  rhythmicContrast: 0.8906479277648032
purpose: []
